version: "2.0"
services:
    ubuntu:
        image: ubuntu:16.04
        restart: always
        ports: 
            - "1234:1234"
    nodejs:
        image: mynodeapp
        restart: always
        ports:
            - "3000:3000"
    nginx:
        image: nginx
        restart: always
        ports: 
            - "8080:80" 
    redis: 
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
    mysql: 
        image: mysql:5.7
        restart: always
        ports: 
            - "27017:27017"